import streamlit as st
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(
    page_title="Saudi Unemployment Forecasting",
    page_icon="📊",
    layout="centered"
)

@st.cache_resource
def load_model():
    return joblib.load("sarima_model.pkl")

try:
    model = load_model()
    model_loaded = True
except:
    model_loaded = False

st.title("📊 Saudi Unemployment Rate Forecasting System")
st.caption("AI3104 — AI System Design | Umm Al-Qura University")
st.markdown("---")

historical = {
    "Quarter": ["2023-Q1","2023-Q2","2023-Q3","2023-Q4",
                "2024-Q1","2024-Q2","2024-Q3","2024-Q4",
                "2025-Q1","2025-Q2","2025-Q3","2025-Q4"],
    "Actual Rate (%)": [8.67, 8.45, 8.81, 7.78,
                        7.61, 7.09, 7.81, 7.00,
                        6.32, 6.78, 7.48, 7.24]
}
df_hist = pd.DataFrame(historical)

st.subheader("🔮 National Unemployment Rate Forecast")

if not model_loaded:
    st.error("Model file not found. Please ensure sarima_model.pkl is in the app directory.")
    st.stop()

mae = 0.4551
forecast_values = model.forecast(steps=2)
forecast_quarters = ["2026-Q1", "2026-Q2"]

forecast_data = []
for i in range(2):
    pred = max(0, forecast_values[i])
    forecast_data.append({
        "Quarter": forecast_quarters[i],
        "Predicted Rate (%)": round(pred, 2),
        "Lower Bound (%)": round(max(0, pred - mae), 2),
        "Upper Bound (%)": round(pred + mae, 2)
    })
df_forecast = pd.DataFrame(forecast_data)

col1, col2 = st.columns(2)
with col1:
    st.metric(
        label="2026-Q1 Forecast",
        value=f"{df_forecast.iloc[0]['Predicted Rate (%)']:.2f}%",
        delta=f"{df_forecast.iloc[0]['Predicted Rate (%)'] - 7.24:.2f}pp vs 2025-Q4"
    )
    st.caption(f"Interval: [{df_forecast.iloc[0]['Lower Bound (%)']:.2f}% — {df_forecast.iloc[0]['Upper Bound (%)']:.2f}%]")

with col2:
    st.metric(
        label="2026-Q2 Forecast",
        value=f"{df_forecast.iloc[1]['Predicted Rate (%)']:.2f}%",
        delta=f"{df_forecast.iloc[1]['Predicted Rate (%)'] - df_forecast.iloc[0]['Predicted Rate (%)']:.2f}pp vs Q1"
    )
    st.caption(f"Interval: [{df_forecast.iloc[1]['Lower Bound (%)']:.2f}% — {df_forecast.iloc[1]['Upper Bound (%)']:.2f}%]")

st.markdown("---")
st.subheader("📈 Historical Trend + Forecast")

fig, ax = plt.subplots(figsize=(11, 5))

ax.plot(df_hist["Quarter"], df_hist["Actual Rate (%)"],
        color="#1f4e79", marker="o", linewidth=2, markersize=6, label="Historical (Actual)")

connect_q = [df_hist["Quarter"].iloc[-1]] + forecast_quarters
connect_v = [df_hist["Actual Rate (%)"].iloc[-1]] + [df_forecast.iloc[i]["Predicted Rate (%)"] for i in range(2)]
connect_lo = [df_hist["Actual Rate (%)"].iloc[-1]] + [df_forecast.iloc[i]["Lower Bound (%)"] for i in range(2)]
connect_hi = [df_hist["Actual Rate (%)"].iloc[-1]] + [df_forecast.iloc[i]["Upper Bound (%)"] for i in range(2)]

ax.plot(connect_q, connect_v,
        color="#2e75b6", marker="s", linewidth=2, markersize=7, linestyle="--", label="Forecast (SARIMA)")
ax.fill_between(connect_q, connect_lo, connect_hi,
                alpha=0.15, color="#2e75b6", label=f"Confidence Interval (±{mae} pp)")
ax.axhline(y=7.0, color="green", linestyle=":", linewidth=1.5, alpha=0.8, label="Vision 2030 Target (7%)")
ax.axvline(x=11.5, color="gray", linestyle="--", linewidth=1, alpha=0.5)
ax.text(11.6, 11.5, "Forecast →", fontsize=8, color="gray")

for i in range(2):
    ax.annotate(
        f"{df_forecast.iloc[i]['Predicted Rate (%)']:.2f}%",
        xy=(forecast_quarters[i], df_forecast.iloc[i]["Predicted Rate (%)"]),
        xytext=(0, 12), textcoords="offset points",
        ha="center", fontsize=9, fontweight="bold", color="#2e75b6"
    )

ax.set_ylabel("Unemployment Rate (%)", fontsize=11)
ax.set_xlabel("Quarter", fontsize=11)
ax.tick_params(axis="x", rotation=45)
ax.legend(fontsize=9)
ax.grid(axis="y", alpha=0.3)
ax.set_ylim(4, 12)
plt.tight_layout()
st.pyplot(fig)

st.markdown("---")
st.subheader("📋 Forecast Details")
st.dataframe(df_forecast, use_container_width=True, hide_index=True)

st.markdown("---")
with st.expander("ℹ️ Model Information"):
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Model", "SARIMA")
    col2.metric("MAE", "0.4551 pp")
    col3.metric("RMSE", "0.5428")
    col4.metric("R²", "0.45")
    st.write("**Training Period:** Q2 2016 — Q2 2023 (27 quarters)")
    st.write("**Test Period:** Q3 2023 — Q4 2025 (12 quarters)")
    st.write("**SARIMA Order:** (1,1,1)(1,1,1,4)")

st.warning("""
⚠️ Disclaimer: These forecasts are statistical projections generated by a SARIMA
time-series model trained on historical data. They are not guaranteed outcomes.
All results should be interpreted as estimates to support decision-making.
""")

st.caption("Data source: DataSaudi — Ministry of Economy and Planning of Saudi Arabia")
